import Image from "next/image"
import Navbar from "apps/client/src/components/Navbar"
import Footer from "apps/client/src/components/Footer"
const Terms =()=>{
    return(
        <>
        <Navbar/>
        <h1>terms & conditions</h1>
        <p>please read all of our terms and conditions before doing anything.</p>
        <Image src={"/terms.jpg"} height={20} width={1200} alt="terms image" className="h-[550px]"/>
        <h1>APOLLO HEALTHCO LIMITED - TERMS OF USE</h1>
        <ol className="list-decimal">
            <li>GENERAL</li>
        </ol>
        <p>1.1.We, at Apollo Healthco Limited, a company duly incorporated under the provisions of the Companies Act, 2013, having its registered office at No.19, Bishop Gardens, R.A. Puram, Chennai, Tamil Nadu -  600028, India (“AHL”, “We”, “Us”, “Our” “Company”) provide services to all individuals accessing or  using our app, Apollo 24|7 and website ( www.apollo247.com ) (collectively “Platform”) for any reason  (“You”, “Yours”, “User”) subject to the notices, terms, and conditions set forth in these Terms of Use  (“Terms of Use”, “Agreement”, “Terms”), read with the Privacy Policy, Return Policy, Payment &  Refunds Policy available here https://www.apollo247.com . AHL and User are hereinafter individually  referred to as the “Party” and collectively as the “Parties”.  
1.2.These Terms of Use together with the Privacy Policy, Return Policy, and Payment and Refund Policy (without limitation) available  either at Platform or entered separately by the Company with You, as applicable, and all other notices,  rules, guidelines with respect to Your use of the Platform, constitutes the entire agreement (“Agreement”) between the Company and You:
1.3.The domain name www.apollo247.com, an internet-based portal, and “Apollo24|7”, a mobile application, is run, operated, and maintained by AHL. AHL may assign, transfer, and subcontract its  rights and/or obligations under these Terms of Use to any third party, as it may deem fit, and you shall  continue to be bound by these Terms of Use in the event of such assignment, transfer, or  subcontracting.
1.4.Our Platform is operated, and services are provided in compliance with the laws in India and AHL shall not be liable to provide any Services availed by you in locations outside India. If you access our services  from locations outside India, you do so at your own risk and you are solely liable for compliance with  applicable local laws. The User agrees to use the services to authorize an individual and get the services  from the third party on his/her behalf. Where you use any third-party website or the services of any  third party, you may be subject to alternative or additional Terms of Use and privacy policies  of the respective third party/s. 
Any accessing or browsing of the Platform and using the Services (as defined in these Terms of Use) indicates your Agreement to all the Terms of Use in this Agreement. If you disagree with any part of the  Terms of Use, then you may discontinue access or use of the Platform.</p>

        <ol className="list-decimal">
            <li>GENERAL</li>
        </ol>
        <p>1.1.We, at Apollo Healthco Limited, a company duly incorporated under the provisions of the Companies Act, 2013, having its registered office at No.19, Bishop Gardens, R.A. Puram, Chennai, Tamil Nadu -  600028, India (“AHL”, “We”, “Us”, “Our” “Company”) provide services to all individuals accessing or  using our app, Apollo 24|7 and website ( www.apollo247.com ) (collectively “Platform”) for any reason  (“You”, “Yours”, “User”) subject to the notices, terms, and conditions set forth in these Terms of Use  (“Terms of Use”, “Agreement”, “Terms”), read with the Privacy Policy, Return Policy, Payment &  Refunds Policy available here https://www.apollo247.com . AHL and User are hereinafter individually  referred to as the “Party” and collectively as the “Parties”.  
1.2.These Terms of Use together with the Privacy Policy, Return Policy, and Payment and Refund Policy (without limitation) available  either at Platform or entered separately by the Company with You, as applicable, and all other notices,  rules, guidelines with respect to Your use of the Platform, constitutes the entire agreement (“Agreement”) between the Company and You:
1.3.The domain name www.apollo247.com, an internet-based portal, and “Apollo24|7”, a mobile application, is run, operated, and maintained by AHL. AHL may assign, transfer, and subcontract its  rights and/or obligations under these Terms of Use to any third party, as it may deem fit, and you shall  continue to be bound by these Terms of Use in the event of such assignment, transfer, or  subcontracting.
1.4.Our Platform is operated, and services are provided in compliance with the laws in India and AHL shall not be liable to provide any Services availed by you in locations outside India. If you access our services  from locations outside India, you do so at your own risk and you are solely liable for compliance with  applicable local laws. The User agrees to use the services to authorize an individual and get the services  from the third party on his/her behalf. Where you use any third-party website or the services of any  third party, you may be subject to alternative or additional Terms of Use and privacy policies  of the respective third party/s. 
Any accessing or browsing of the Platform and using the Services (as defined in these Terms of Use) indicates your Agreement to all the Terms of Use in this Agreement. If you disagree with any part of the  Terms of Use, then you may discontinue access or use of the Platform.</p>

        <ol className="list-decimal">
            <li>GENERAL</li>
        </ol>
        <p>1.1.We, at Apollo Healthco Limited, a company duly incorporated under the provisions of the Companies Act, 2013, having its registered office at No.19, Bishop Gardens, R.A. Puram, Chennai, Tamil Nadu -  600028, India (“AHL”, “We”, “Us”, “Our” “Company”) provide services to all individuals accessing or  using our app, Apollo 24|7 and website ( www.apollo247.com ) (collectively “Platform”) for any reason  (“You”, “Yours”, “User”) subject to the notices, terms, and conditions set forth in these Terms of Use  (“Terms of Use”, “Agreement”, “Terms”), read with the Privacy Policy, Return Policy, Payment &  Refunds Policy available here https://www.apollo247.com . AHL and User are hereinafter individually  referred to as the “Party” and collectively as the “Parties”.  
1.2.These Terms of Use together with the Privacy Policy, Return Policy, and Payment and Refund Policy (without limitation) available  either at Platform or entered separately by the Company with You, as applicable, and all other notices,  rules, guidelines with respect to Your use of the Platform, constitutes the entire agreement (“Agreement”) between the Company and You:
1.3.The domain name www.apollo247.com, an internet-based portal, and “Apollo24|7”, a mobile application, is run, operated, and maintained by AHL. AHL may assign, transfer, and subcontract its  rights and/or obligations under these Terms of Use to any third party, as it may deem fit, and you shall  continue to be bound by these Terms of Use in the event of such assignment, transfer, or  subcontracting.
1.4.Our Platform is operated, and services are provided in compliance with the laws in India and AHL shall not be liable to provide any Services availed by you in locations outside India. If you access our services  from locations outside India, you do so at your own risk and you are solely liable for compliance with  applicable local laws. The User agrees to use the services to authorize an individual and get the services  from the third party on his/her behalf. Where you use any third-party website or the services of any  third party, you may be subject to alternative or additional Terms of Use and privacy policies  of the respective third party/s. 
Any accessing or browsing of the Platform and using the Services (as defined in these Terms of Use) indicates your Agreement to all the Terms of Use in this Agreement. If you disagree with any part of the  Terms of Use, then you may discontinue access or use of the Platform.</p>

        <ol className="list-decimal">
            <li>GENERAL</li>
        </ol>
        <p>1.1.We, at Apollo Healthco Limited, a company duly incorporated under the provisions of the Companies Act, 2013, having its registered office at No.19, Bishop Gardens, R.A. Puram, Chennai, Tamil Nadu -  600028, India (“AHL”, “We”, “Us”, “Our” “Company”) provide services to all individuals accessing or  using our app, Apollo 24|7 and website ( www.apollo247.com ) (collectively “Platform”) for any reason  (“You”, “Yours”, “User”) subject to the notices, terms, and conditions set forth in these Terms of Use  (“Terms of Use”, “Agreement”, “Terms”), read with the Privacy Policy, Return Policy, Payment &  Refunds Policy available here https://www.apollo247.com . AHL and User are hereinafter individually  referred to as the “Party” and collectively as the “Parties”.  
1.2.These Terms of Use together with the Privacy Policy, Return Policy, and Payment and Refund Policy (without limitation) available  either at Platform or entered separately by the Company with You, as applicable, and all other notices,  rules, guidelines with respect to Your use of the Platform, constitutes the entire agreement (“Agreement”) between the Company and You:
1.3.The domain name www.apollo247.com, an internet-based portal, and “Apollo24|7”, a mobile application, is run, operated, and maintained by AHL. AHL may assign, transfer, and subcontract its  rights and/or obligations under these Terms of Use to any third party, as it may deem fit, and you shall  continue to be bound by these Terms of Use in the event of such assignment, transfer, or  subcontracting.
1.4.Our Platform is operated, and services are provided in compliance with the laws in India and AHL shall not be liable to provide any Services availed by you in locations outside India. If you access our services  from locations outside India, you do so at your own risk and you are solely liable for compliance with  applicable local laws. The User agrees to use the services to authorize an individual and get the services  from the third party on his/her behalf. Where you use any third-party website or the services of any  third party, you may be subject to alternative or additional Terms of Use and privacy policies  of the respective third party/s. 
Any accessing or browsing of the Platform and using the Services (as defined in these Terms of Use) indicates your Agreement to all the Terms of Use in this Agreement. If you disagree with any part of the  Terms of Use, then you may discontinue access or use of the Platform.</p>

        <Footer/>
        </>
    )
}

export default Terms