import Image from "next/image"
import Navbar from "apps/client/src/components/Navbar"
import Footer from "apps/client/src/components/Footer"
const PrivacyPolicy =()=>{
    return(
        <div>
            <Navbar/>
            <h1>Apollo 247 Privacy Policy</h1>
            <Image src={"/policy-image.jpg"} alt="policy image" width={1200} height={20}/>
            <p>APOLLO HEALTHCO LIMITED-PRIVACY POLICY </p>

            <p>This Privacy Policy governs how we, Apollo Healthco Limited, a company duly incorporated under the provisions of the Companies Act, 2013, having its registered office at 19, Bishop Gardens, R. A. Puram, Chennai, Tamil Nadu - 600028, India (collectively, “AHL”, “Apollo”, “Company”, “we,” “us,” or “our”) collect, use, share and process your information, that you provide to us through your use of the app,  Apollo 24|7 and website [https://www.apollo247.com/] in the course of availing services that are  made available on the said app and website (“Services”) as defined in the Terms of Use [https://www.apollo247.com/terms] to you. </p>

            <p>AHL, owner of the Apollo 24|7 website and app (“Website” / “App” respectively), respects your  privacy, and seeks to comply with applicable legal requirements, including the Information Technology  Act, 2000 and the Information Technology (Reasonable Security Practices and Procedures and  Sensitive Personal Information) Rules, 2011 (the “SPDI Rules”) as amended from time to time, in  respect of data collection, processing, and transfer. </p>

            <p>Please read this Privacy Policy carefully. By accessing or using this Website/ App, you agree to be  bound by the terms described herein and all the terms incorporated by reference. If you do not agree  to all of these terms, do not use this Website/ App. </p>

            <ol className="list-decimal">
                <li>WHAT IS PERSONAL INFORMATION </li>

                <ol type="a">
                    <li> Personal information is that information which can be used to directly or indirectly identify you. It includes de-identified data that, when linked to other information available to us, would enable us to identify you. Personal data does not include data that has been irreversibly anonymized or aggregated  so that we cannot identify you through it, even in conjugation conjunction with other information. </li>
                    <li>“Sensitive Personal Data or Information” means personal information of any individual relating to password; financial information such as bank account or credit card or debit card or other payment  instrument details; physical, physiological, and mental health condition; sexual orientation; health  information such as medical records and history; biometric information; any detail relating to the  above as provided to or received by us for processing or storage. However, any data/information  relating to an individual that is freely available or accessible in the public domain or furnished under  the Right to Information Act, 2005, or any other law shall not qualify as Sensitive Personal Data or  Information. </li>
                    <li>By signing up on the App or proceeding to the Website, and / or using our Services you represent that you voluntarily provide us with personal information including medical and financial information, and  consent to their collection, use, and disclosure in accordance with this Privacy Policy. You also  represent that you are duly authorized by any third party (including a child or an employee) whose  information you share with us. We shall act as per your representation of authority and shall not make  any independent enquiries to ascertain the veracity of your authorization. In the event you do not  have sufficient authorization you shall be solely responsible for your acts and omissions including  sharing of information with us by you and the consequential processing and actions taken by us in  accordance with this Privacy Policy. </li>
                </ol>
            </ol>
                        <ol className="list-decimal">
                <li>WHAT IS PERSONAL INFORMATION </li>

                <ol type="a">
                    <li> Personal information is that information which can be used to directly or indirectly identify you. It includes de-identified data that, when linked to other information available to us, would enable us to identify you. Personal data does not include data that has been irreversibly anonymized or aggregated  so that we cannot identify you through it, even in conjugation conjunction with other information. </li>
                    <li>“Sensitive Personal Data or Information” means personal information of any individual relating to password; financial information such as bank account or credit card or debit card or other payment  instrument details; physical, physiological, and mental health condition; sexual orientation; health  information such as medical records and history; biometric information; any detail relating to the  above as provided to or received by us for processing or storage. However, any data/information  relating to an individual that is freely available or accessible in the public domain or furnished under  the Right to Information Act, 2005, or any other law shall not qualify as Sensitive Personal Data or  Information. </li>
                    <li>By signing up on the App or proceeding to the Website, and / or using our Services you represent that you voluntarily provide us with personal information including medical and financial information, and  consent to their collection, use, and disclosure in accordance with this Privacy Policy. You also  represent that you are duly authorized by any third party (including a child or an employee) whose  information you share with us. We shall act as per your representation of authority and shall not make  any independent enquiries to ascertain the veracity of your authorization. In the event you do not  have sufficient authorization you shall be solely responsible for your acts and omissions including  sharing of information with us by you and the consequential processing and actions taken by us in  accordance with this Privacy Policy. </li>
                </ol>
            </ol>
                        <ol className="list-decimal">
                <li>WHAT IS PERSONAL INFORMATION </li>

                <ol type="a">
                    <li> Personal information is that information which can be used to directly or indirectly identify you. It includes de-identified data that, when linked to other information available to us, would enable us to identify you. Personal data does not include data that has been irreversibly anonymized or aggregated  so that we cannot identify you through it, even in conjugation conjunction with other information. </li>
                    <li>“Sensitive Personal Data or Information” means personal information of any individual relating to password; financial information such as bank account or credit card or debit card or other payment  instrument details; physical, physiological, and mental health condition; sexual orientation; health  information such as medical records and history; biometric information; any detail relating to the  above as provided to or received by us for processing or storage. However, any data/information  relating to an individual that is freely available or accessible in the public domain or furnished under  the Right to Information Act, 2005, or any other law shall not qualify as Sensitive Personal Data or  Information. </li>
                    <li>By signing up on the App or proceeding to the Website, and / or using our Services you represent that you voluntarily provide us with personal information including medical and financial information, and  consent to their collection, use, and disclosure in accordance with this Privacy Policy. You also  represent that you are duly authorized by any third party (including a child or an employee) whose  information you share with us. We shall act as per your representation of authority and shall not make  any independent enquiries to ascertain the veracity of your authorization. In the event you do not  have sufficient authorization you shall be solely responsible for your acts and omissions including  sharing of information with us by you and the consequential processing and actions taken by us in  accordance with this Privacy Policy. </li>
                </ol>
            </ol>
                        <ol className="list-decimal">
                <li>WHAT IS PERSONAL INFORMATION </li>

                <ol type="a">
                    <li> Personal information is that information which can be used to directly or indirectly identify you. It includes de-identified data that, when linked to other information available to us, would enable us to identify you. Personal data does not include data that has been irreversibly anonymized or aggregated  so that we cannot identify you through it, even in conjugation conjunction with other information. </li>
                    <li>“Sensitive Personal Data or Information” means personal information of any individual relating to password; financial information such as bank account or credit card or debit card or other payment  instrument details; physical, physiological, and mental health condition; sexual orientation; health  information such as medical records and history; biometric information; any detail relating to the  above as provided to or received by us for processing or storage. However, any data/information  relating to an individual that is freely available or accessible in the public domain or furnished under  the Right to Information Act, 2005, or any other law shall not qualify as Sensitive Personal Data or  Information. </li>
                    <li>By signing up on the App or proceeding to the Website, and / or using our Services you represent that you voluntarily provide us with personal information including medical and financial information, and  consent to their collection, use, and disclosure in accordance with this Privacy Policy. You also  represent that you are duly authorized by any third party (including a child or an employee) whose  information you share with us. We shall act as per your representation of authority and shall not make  any independent enquiries to ascertain the veracity of your authorization. In the event you do not  have sufficient authorization you shall be solely responsible for your acts and omissions including  sharing of information with us by you and the consequential processing and actions taken by us in  accordance with this Privacy Policy. </li>
                </ol>
            </ol>
                        <ol className="list-decimal">
                <li>WHAT IS PERSONAL INFORMATION </li>

                <ol type="a">
                    <li> Personal information is that information which can be used to directly or indirectly identify you. It includes de-identified data that, when linked to other information available to us, would enable us to identify you. Personal data does not include data that has been irreversibly anonymized or aggregated  so that we cannot identify you through it, even in conjugation conjunction with other information. </li>
                    <li>“Sensitive Personal Data or Information” means personal information of any individual relating to password; financial information such as bank account or credit card or debit card or other payment  instrument details; physical, physiological, and mental health condition; sexual orientation; health  information such as medical records and history; biometric information; any detail relating to the  above as provided to or received by us for processing or storage. However, any data/information  relating to an individual that is freely available or accessible in the public domain or furnished under  the Right to Information Act, 2005, or any other law shall not qualify as Sensitive Personal Data or  Information. </li>
                    <li>By signing up on the App or proceeding to the Website, and / or using our Services you represent that you voluntarily provide us with personal information including medical and financial information, and  consent to their collection, use, and disclosure in accordance with this Privacy Policy. You also  represent that you are duly authorized by any third party (including a child or an employee) whose  information you share with us. We shall act as per your representation of authority and shall not make  any independent enquiries to ascertain the veracity of your authorization. In the event you do not  have sufficient authorization you shall be solely responsible for your acts and omissions including  sharing of information with us by you and the consequential processing and actions taken by us in  accordance with this Privacy Policy. </li>
                </ol>
            </ol>
                        <ol className="list-decimal">
                <li>WHAT IS PERSONAL INFORMATION </li>

                <ol type="a">
                    <li> Personal information is that information which can be used to directly or indirectly identify you. It includes de-identified data that, when linked to other information available to us, would enable us to identify you. Personal data does not include data that has been irreversibly anonymized or aggregated  so that we cannot identify you through it, even in conjugation conjunction with other information. </li>
                    <li>“Sensitive Personal Data or Information” means personal information of any individual relating to password; financial information such as bank account or credit card or debit card or other payment  instrument details; physical, physiological, and mental health condition; sexual orientation; health  information such as medical records and history; biometric information; any detail relating to the  above as provided to or received by us for processing or storage. However, any data/information  relating to an individual that is freely available or accessible in the public domain or furnished under  the Right to Information Act, 2005, or any other law shall not qualify as Sensitive Personal Data or  Information. </li>
                    <li>By signing up on the App or proceeding to the Website, and / or using our Services you represent that you voluntarily provide us with personal information including medical and financial information, and  consent to their collection, use, and disclosure in accordance with this Privacy Policy. You also  represent that you are duly authorized by any third party (including a child or an employee) whose  information you share with us. We shall act as per your representation of authority and shall not make  any independent enquiries to ascertain the veracity of your authorization. In the event you do not  have sufficient authorization you shall be solely responsible for your acts and omissions including  sharing of information with us by you and the consequential processing and actions taken by us in  accordance with this Privacy Policy. </li>
                </ol>
            </ol>
                        <ol className="list-decimal">
                <li>WHAT IS PERSONAL INFORMATION </li>

                <ol type="a">
                    <li> Personal information is that information which can be used to directly or indirectly identify you. It includes de-identified data that, when linked to other information available to us, would enable us to identify you. Personal data does not include data that has been irreversibly anonymized or aggregated  so that we cannot identify you through it, even in conjugation conjunction with other information. </li>
                    <li>“Sensitive Personal Data or Information” means personal information of any individual relating to password; financial information such as bank account or credit card or debit card or other payment  instrument details; physical, physiological, and mental health condition; sexual orientation; health  information such as medical records and history; biometric information; any detail relating to the  above as provided to or received by us for processing or storage. However, any data/information  relating to an individual that is freely available or accessible in the public domain or furnished under  the Right to Information Act, 2005, or any other law shall not qualify as Sensitive Personal Data or  Information. </li>
                    <li>By signing up on the App or proceeding to the Website, and / or using our Services you represent that you voluntarily provide us with personal information including medical and financial information, and  consent to their collection, use, and disclosure in accordance with this Privacy Policy. You also  represent that you are duly authorized by any third party (including a child or an employee) whose  information you share with us. We shall act as per your representation of authority and shall not make  any independent enquiries to ascertain the veracity of your authorization. In the event you do not  have sufficient authorization you shall be solely responsible for your acts and omissions including  sharing of information with us by you and the consequential processing and actions taken by us in  accordance with this Privacy Policy. </li>
                </ol>
            </ol>
                        <ol className="list-decimal">
                <li>WHAT IS PERSONAL INFORMATION </li>

                <ol type="a">
                    <li> Personal information is that information which can be used to directly or indirectly identify you. It includes de-identified data that, when linked to other information available to us, would enable us to identify you. Personal data does not include data that has been irreversibly anonymized or aggregated  so that we cannot identify you through it, even in conjugation conjunction with other information. </li>
                    <li>“Sensitive Personal Data or Information” means personal information of any individual relating to password; financial information such as bank account or credit card or debit card or other payment  instrument details; physical, physiological, and mental health condition; sexual orientation; health  information such as medical records and history; biometric information; any detail relating to the  above as provided to or received by us for processing or storage. However, any data/information  relating to an individual that is freely available or accessible in the public domain or furnished under  the Right to Information Act, 2005, or any other law shall not qualify as Sensitive Personal Data or  Information. </li>
                    <li>By signing up on the App or proceeding to the Website, and / or using our Services you represent that you voluntarily provide us with personal information including medical and financial information, and  consent to their collection, use, and disclosure in accordance with this Privacy Policy. You also  represent that you are duly authorized by any third party (including a child or an employee) whose  information you share with us. We shall act as per your representation of authority and shall not make  any independent enquiries to ascertain the veracity of your authorization. In the event you do not  have sufficient authorization you shall be solely responsible for your acts and omissions including  sharing of information with us by you and the consequential processing and actions taken by us in  accordance with this Privacy Policy. </li>
                </ol>
            </ol>
            <Footer/>
        </div>
    )
}


export default PrivacyPolicy