import './global.css';
import {GoogleOAuthProvider} from "@react-oauth/google"
export const metadata = {
  title: 'Care Hub',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const id = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || process.env.GOOGLE_CLIENT_ID || '';
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Google+Sans:ital,opsz,wght@0,17..18,400..700;1,17..18,400..700&display=swap" rel="stylesheet" />
      </head>
      <body className='max-w-full mx-auto '>
        <GoogleOAuthProvider clientId={id}>
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
