import './global.css';

export const metadata = {
  title: 'Care Hub',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='max-w-7xl mx-auto px-6'>{children}</body>
    </html>
  );
}
